# версия compose file
version: '3'
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes: ['.api:/api']
    links:
      - redis

  worker:
    build:
      context: ./celery_queue
      dockerfile: Dockerfile
    command: celery -A tasks worker -l info -E
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

    # https://github.com/mattkohl/docker-flask-celery-redis
