version: '3'
services:
  web:
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./:/app
    links:
      - redis

  worker:
    build:
      context: ./celery_queue
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - redis
    command: celery -A tasks worker -l info -E

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  monitor:
    build:
      context: ./celery_queue
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    command: celery -A tasks flower
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - worker
    volumes: ['./celery_queue:/queue']


